// Regenerates `src/config/emojiAliases.ts` from the full table in
// `src/config/emojis.ts`. Run after adding or renaming emoji:
//
//   node scripts/genEmojiAliases.mjs
//
// `src/config/__tests__/emojiAliases.spec.ts` fails while the two disagree.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const configDir = resolve(dirname(fileURLToPath(import.meta.url)), '../src/config')
const source = readFileSync(resolve(configDir, 'emojis.ts'), 'utf8')

// The table is a plain literal, so it is read by shape rather than compiled.
const entry = /\{\s*emoji:\s*'((?:[^'\\]|\\.)*)',[\s\S]*?aliases:\s*\[([^\]]*)\]/g
const map = new Map()
for (const [, emoji, aliasList] of source.matchAll(entry)) {
  for (const [, alias] of aliasList.matchAll(/'((?:[^'\\]|\\.)*)'/g)) {
    // First entry wins, matching the lookup the full table used to do.
    if (!map.has(alias)) map.set(alias, emoji)
  }
}

if (map.size === 0) throw new Error('no emoji parsed — has the table changed shape?')

const body = [...map].map(([alias, emoji]) => `    '${alias}': '${emoji}',`).join('\n')

writeFileSync(
  resolve(configDir, 'emojiAliases.ts'),
  `// Alias -> character map derived from \`emojis.ts\`, which also carries the
// descriptions, categories and tags the emoji picker needs. Rendering \`:alias:\`
// only needs the character, and pulling the full table in for that put ~230KB
// of picker metadata in the startup bundle.
//
// Generated by \`scripts/genEmojiAliases.mjs\`;
// \`__tests__/emojiAliases.spec.ts\` fails if the two drift apart.
const emojiAliases: Record<string, string> = {
${body}
};

export default emojiAliases;
`,
  'utf8'
)

console.log(`emojiAliases.ts: ${map.size} aliases`)
